version: '3'
services:
  produit-ms:
    image: jugo835/produit-ms:latest
    ports:
      - "8000:8000"
    environment:
      - ENV=dev

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # changer ce mot de passe pour la prod
    depends_on:
      - prometheus
