"""Ajout de la table prices

Revision ID: 0202e069e7c2
Revises: d163ec092d01
Create Date: 2025-04-15 17:42:32.351248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0202e069e7c2'
down_revision: Union[str, None] = 'd163ec092d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_id', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='prices_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='prices_pkey')
    )
    op.create_index('ix_prices_id', 'prices', ['id'], unique=False)
    # ### end Alembic commands ###
