"""Ajout champ date_added dans Product

Revision ID: 41da1866e2ea
Revises: 
Create Date: 2025-04-15 15:29:08.973543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41da1866e2ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_produit', sa.String(), nullable=False))
    op.add_column('products', sa.Column('prix_unitaire', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('QTTStock', sa.Integer(), nullable=False))
    op.drop_column('products', 'name')
    op.drop_column('products', 'price')
    op.drop_column('products', 'quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('products', 'QTTStock')
    op.drop_column('products', 'prix_unitaire')
    op.drop_column('products', 'name_produit')
    # ### end Alembic commands ###
