"""Ajout de la table prices

Revision ID: d163ec092d01
Revises: c7bca20c9e81
Create Date: 2025-04-15 17:40:51.649778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd163ec092d01'
down_revision: Union[str, None] = 'c7bca20c9e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prices_id', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='prices_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prices_pkey')
    )
    op.create_index('ix_prices_id', 'prices', ['id'], unique=False)
    # ### end Alembic commands ###
