"""Ajout du champ created_at dans Product

Revision ID: d73b1adb717d
Revises: 41da1866e2ea
Create Date: 2025-04-15 16:08:34.714013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73b1adb717d'
down_revision: Union[str, None] = '41da1866e2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(), nullable=False))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('products', 'prix_unitaire')
    op.drop_column('products', 'QTTStock')
    op.drop_column('products', 'name_produit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name_produit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('QTTStock', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('prix_unitaire', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
